name: quantified-self

services:
  influxdb2:
    image: influxdb:2
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: wildpress
      DOCKER_INFLUXDB_INIT_BUCKET: quantified-self
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-storage:

secrets:
  influxdb2-admin-username:
    environment: INFLUXDB2_ADMIN_USERNAME
  influxdb2-admin-password:
    environment: INFLUXDB2_ADMIN_PASSWORD
  influxdb2-admin-token:
    environment: INFLUXDB2_ADMIN_TOKEN
